### ISSUE TITLE
Feat: migrate from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by lirantal** [lirantal/snyk-or-snick#4]

**Comment by Pavan-Nambi** [comment]
hey @lirantal  should i just delete .circleci and make workflows in .github thats it right? i have never done this before so not sure.....

**Comment by lirantal** [comment]
Hi Pavan, that's correct.
Create a pull request that removes all of the CircleCI configuration file and instead introduces a GitHub Actions workflow that corresponds to what the CircleCI config did.

**Comment by lirantal** [comment]
Done with #5
